// Code generated by goctl. DO NOT EDIT!
// Source: course.proto

package server

import (
	"context"

	"course/course/rpc/internal/logic"
	"course/course/rpc/internal/svc"
	"course/course/rpc/types/course"
)

type CourseServiceServer struct {
	svcCtx *svc.ServiceContext
	course.UnimplementedCourseServiceServer
}

func NewCourseServiceServer(svcCtx *svc.ServiceContext) *CourseServiceServer {
	return &CourseServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CourseServiceServer) CreateCourse(ctx context.Context, in *course.CreateCourseRequest) (*course.CreateCourseResponse, error) {
	l := logic.NewCreateCourseLogic(ctx, s.svcCtx)
	return l.CreateCourse(in)
}

func (s *CourseServiceServer) DeleteCourse(ctx context.Context, in *course.DeleteCourseRequest) (*course.DeleteCourseResponse, error) {
	l := logic.NewDeleteCourseLogic(ctx, s.svcCtx)
	return l.DeleteCourse(in)
}

func (s *CourseServiceServer) UpdateCourse(ctx context.Context, in *course.UpdateCourseRequest) (*course.UpdateCourseResponse, error) {
	l := logic.NewUpdateCourseLogic(ctx, s.svcCtx)
	return l.UpdateCourse(in)
}

func (s *CourseServiceServer) MGetCourse(ctx context.Context, in *course.MGetCourseRequest) (*course.MGetCourseResponse, error) {
	l := logic.NewMGetCourseLogic(ctx, s.svcCtx)
	return l.MGetCourse(in)
}

func (s *CourseServiceServer) CheckCourse(ctx context.Context, in *course.CheckCourseRequest) (*course.CheckCourseResponse, error) {
	l := logic.NewCheckCourseLogic(ctx, s.svcCtx)
	return l.CheckCourse(in)
}

func (s *CourseServiceServer) QueryCourseBySid(ctx context.Context, in *course.QueryCourseBySidRequest) (*course.QueryCourseBySidResponse, error) {
	l := logic.NewQueryCourseBySidLogic(ctx, s.svcCtx)
	return l.QueryCourseBySid(in)
}
