// Code generated by goctl. DO NOT EDIT.
package types

type Course struct {
	Id     int32  `json:"id"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
	Hours  int32  `json:"hours"`
	Sid    int32  `json:"sid"`
	SName  string `json:"sname"`
}

type BaseResponse struct {
	Status  int32       `json:"status"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type CourseReq struct {
	Id int32 `path:"id"`
}

type MCourseReq struct {
	Sid  int32 `json:"sid"`
	Page int32 `json:"page"`
	Size int32 `json:"size"`
}

type MCourseRes struct {
	Courses []*Course `json:"courses"`
	Total   int32     `json:"total"`
}

type NameCheckReq struct {
	Name string `json:"name"`
}

type CreateCourseReq struct {
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
	Hours  int32  `json:"hours"`
	Sid    int32  `json:"sid"`
}

type QuerySchoolIdReq struct {
	Name string `json:"name"`
}

type UpdateCourseReq struct {
	Id     int32  `path:"id"`
	Name   string `json:"name"`
	Avatar string `json:"avatar,omitempty"`
	Hours  int32  `json:"hours"`
	Sid    int32  `json:"sid"`
}

type DeleteCourseReq struct {
	Id int32 `path:"id"`
}

type DownloadRequest struct {
	File string `path:"file"`
}

type UploadResponse struct {
	Name string `json:"name"`
	Size int64  `json:"size"`
}
