// Code generated by goctl. DO NOT EDIT!
// Source: school.proto

package server

import (
	"context"

	"course/school/rpc/internal/logic"
	"course/school/rpc/internal/svc"
	"course/school/rpc/types/school"
)

type SchoolServiceServer struct {
	svcCtx *svc.ServiceContext
	school.UnimplementedSchoolServiceServer
}

func NewSchoolServiceServer(svcCtx *svc.ServiceContext) *SchoolServiceServer {
	return &SchoolServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SchoolServiceServer) MGetSchool(ctx context.Context, in *school.MGetSchoolRequest) (*school.MGetSchoolResponse, error) {
	l := logic.NewMGetSchoolLogic(ctx, s.svcCtx)
	return l.MGetSchool(in)
}

func (s *SchoolServiceServer) QueryIdByName(ctx context.Context, in *school.QueryIdByNameRequest) (*school.QueryIdByNameResponse, error) {
	l := logic.NewQueryIdByNameLogic(ctx, s.svcCtx)
	return l.QueryIdByName(in)
}
