// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"course/course/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/courses/:id",
				Handler: getCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/courses/school",
				Handler: getMCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/courses/:id",
				Handler: updateCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/courses",
				Handler: createCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/courses/:id",
				Handler: deleteCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/courses/nameCheck",
				Handler: nameCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/oss/:file",
				Handler: DownloadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oss/upload",
				Handler: UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/courses/schoolId",
				Handler: QuerySchoolIdHandler(serverCtx),
			},
		},
	)
}
